### ISSUE TITLE
Vista GUI para la gestión de cliente (sin comportamiento, solo la interface)

### ISSUE THREAD

**Issue by ivannieto** [kant003/Store#4]

**Comment by kant003** [comment]
La interface tendrá 2 partes, que deberán quedar como se ve en la imagen:

![a](https://cloud.githubusercontent.com/assets/3658264/19717560/809d26f4-9b61-11e6-915e-be03691432fe.png)
![b](https://cloud.githubusercontent.com/assets/3658264/19718220/ae930b5c-9b64-11e6-8f10-a84587268ade.png)

Esta interfaz se podrá diseñar con un CardLayout (con 2 jpanel en su interior).

**1er panel:**
Desde la cual se podrán ver todos los clientes guardados, se podrá borrar, editar y añadir nuevos clientes, así como refrescar los datos y realizar filtrados.
El interface estará compuesta por un JFrame principal en cuyo interior habrá un jtable (de nombre tableClientes) en el centro y 4 botones en la parte inferior.(buttonDelete, buttonUpdate, buttonAdd y buttonRefresh)
En la parte superior un label con el titulo de la ventana y una zona para que se pueden filtrar los datos a modo de búsqueda txtFilter.

**2º panel**
Necesitaremos crear otro panel con un formulario para poder editar y añadir nuevos clientes.
En este caso será un JDialog que contendrá en su interior labels y cajas de textos (txtId, txtName, txtSurnames, txtTelephone, txtEmail, txtAddress)
Y 2 botones para guardar/actualizar y cancelar

Nota el campo txtId no será editable por el usuario.
